server:
  port: 9093

eureka:
  instance:
    hostname: eureka-server
    port: 9091
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka-server:9091/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000

spring:
  data:
    mongodb:
      host: mongodb
      port: 27017
      database: mp_ocorrencias
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

## Configuring info endpoint
info:
  app:
    name: Ocorrencia Server
    description: Backend do servidor de ocorrencias
    version: 1.0.0
